# fly.toml app configuration file generated for workout-journal-backend-flyio-spring-glitter-2984 on 2024-04-25T10:47:13+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'workout-journal-backend-flyio-spring-glitter-2984'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
